### ISSUE TITLE
Please document your point of view regarding GPLv2 and its implications

### ISSUE THREAD

**Issue by mpdude** [woothemes/FlexSlider#1240]
I have spent quite some time figuring out how the GPL has to be interpreted for Javascript in particular. There is no "official" statement (for example by the FSF) on that subject. Some points I find noteworthy:

* Using a Javascript in your website implies "distributing", as the code is transferred to other machines and executed there.
* Concatenated and especially minified JavaScript is not "open source" in the sense of the GPL as it cannot be directly understood or reviewed by a human. De-obfuscation would be required just as de-compilation would be needed for classical binaries. In the GPL, the "source" is "the preferred form of the work for making changes", which the result of minification clearly is not.
* The GPL itself remains vague of what constitutes a "derived work", especially with regards to calling the APIs of libraries.

So, could you (@mattyza?) as the original copyright holder please clarify the following items?

1. When I use FlexSlider in a publicly accessible website along with other (self-written or otherwise obtained) JavaScript code, and that code calls methods of the FlexSlider API, do I need to make this "other" code available under GPL as well?

2. Does it make a difference whether the FlexSlider code is referenced with its own `<script>` tag, is part of a concatenated or concatenated+minified JavaScript file?

3. Will I need to state on the website somewhere that FlexSlider is used to give you the proper attribution, or is preserving comments in the code sufficient?

Thanks a lot!

**Comment by dspnorman** [comment]
@mattyza I'd also appreciate hearing your thoughts on the questions @mpdude raises in the previous comment. I was surprised to find this issue marked as closed without at least a little more explanation (the commit from @jeffikus seems to be a simple clarification of the original language).

I would be very pleased if you'd be will to consider a dual license approach.

Thanks!

**Comment by mattyza** [comment]
@mpdude @dspnorman I'm sorry for the delay here. I'll clarify.

The GPL is an irrevocable license. Thus, "switching" to an alternate license isn't an option. Dual licensing is an option, yet doesn't really achieve the results you're looking for, as the GPL would still apply (it seems you'd prefer MIT over GPL, rather than both?).

A "derivative work" is defined, as I see it, as a new project which stems from the core of another project. Thus, if someone decided to fork FlexSlider and create for example, FlexibleSlider, this would be a new project using the code from FlexSlider. This would require that the FlexibleSlider project remain GPL-licensed and attribution given to the authors of FlexSlider.

Here's an alternate example of how the GPL applies in a slightly different context.

If I'm building a WordPress-powered website, any WordPress plugins or themes I develop for this project are automatically GPL-licensed, as WordPress is GPL-licensed and the WordPress plugins and themes rely on WordPress in order to function.

If I'm building a separate SaaS-based project, for example, which leverages the WordPress API to perform say, a reporting task, this code doesn't rely on WordPress in order to function, yet leverages a WordPress API. This API could easily be replaced by another API at any time, therefore the SaaS project doesn't *rely* on WordPress and isn't required to be GPL-licensed.

Thus, using FlexSlider in a project is entirely fine, without requiring that your code is all GPL (unless you develop new code which directly relies on FlexSlider- ie: a FlexSlider extension).

I hope this helps to clarify. :)

**Comment by mpdude** [comment]
For me, I can live with that. Thanks! 

Just for the record, there's an article by the FSF that deals with JavaScript, but it does not really clear this particular issue: http://www.gnu.org/philosophy/javascript-trap.html

However, it shows that the FSF considers compressed/minified (and possibly concatenated) JavaScript a "compiled" (thus, not open-source) format. And by putting it on a webserver and referring to it from a publicly accessible website, you're (possibly) "distributing" it.

If FlexSlider were dual-licensed, I could choose to go with the MIT license and not have this ambiguity.

**Comment by mattyza** [comment]
@mpdude I could be mistaken, although I don't believe that's how dual-licensing works (that you choose which license you prescribe to), especially since the GPL is irrevocable. "Choosing" between GPL or MIT on a dual-licensed project would be the same as "revoking" the GPL, as I see it, which isn't possible. :)
