### ISSUE TITLE
FlexSlider width calculation bug, pushing content left and showing part of next slide.

### ISSUE THREAD

**Issue by peterfinlan** [woothemes/FlexSlider#1263]
Hi there

I'm having an intermittent problem in all browsers with the first FlexSlider on a website I am working on at the moment. Intermittently, on load, the LI's inside the FlexSlider seem to be being pushed to the left by about 10-15px, thus displaying the first 10-15px of the next slide. See screenshot here: http://goo.gl/N3xOsa. Has anyone else had this problem? Live preview here: http://goo.gl/3rxYqr.

This problem is intermittent, refresh browser until it appears.

Thanks.

**Comment by matdave** [comment]
+1 I am having the same problem

**Comment by matdave** [comment]
it appears to go away when I change the animation to "fade"

**Comment by peterfinlan** [comment]
Hey matdave, Yes I should have mentioned that this bug only appears to happen while using the "slide" animation type. It does not happen while using "fade". It appears to be a width calculation problem involving the browser scrollbar width, intermittently. I'd love to know how to overcome this.. I've tried just about everything I know..

**Comment by Spongsta** [comment]
@matdave & @peterfinlan. I had a similar issue when my flexslider contained just text elements. Have you tried removing the padding from your parent container (@peterfinlan - in your case the .features-slider div) and adding it to a wrapper div inside of the list items?  This was exactly what I was doing and removing it from a parent div and using it on a wrapper div inside the list item seemed to correct this issue for me. e.g.
```html
<div class="flexslider-wrapper"> <!-- no padding -->
    <div class="flexslider">
        <ul class="slides">
            <li class="slide">
                <div class="text-wrapper"> <!-- padding goes on .text-wrapper -->
                    <!-- text elements -->
                </div>
            </li>
        </ul>
    </div>
</div>
```

I created some codepens for examples - please note that since I had to load the flexslider in via a CDN it still has a line of code that is a know bug (i think it's issue#975?) that I'm unable to comment out so you'll note that I'm beginning the slider at `startAt: 1` so as to avoid any confusion when initially viewing the slider.

[Reported Issue](http://codepen.io/spongsta/pen/gbGjJw) note: you'll need to look closely for the white text from the next slide creeping into view as similar to what you reported (and I've seen here http://goo.gl/3rxYqr).  Another item to note is the pesky control nav way down the bottom - this is due to not using the `.flexslider` class with your instantiated div.

[My working solution](http://codepen.io/spongsta/pen/VYMBNY) note: also includes a css "trick" to fix the control nav issue if you don't want to use `.flexslider` - fair warning here, you'll need to accommodate for the control nav with any other subsequent elements with this solution, easiest thing to do is just use `.flexslider` and manipulate the controlNav with a nice `text-align:left;`

HTH,
Spongsta

**Comment by jeffikus** [comment]
Hi guys, the flex version on the site is 2.2.2 - please update to at least the 2.4.0 release and reopen if the issue persists.

**Comment by xbroak** [comment]
Still an issue on the latest version

**Comment by jeffikus** [comment]
@xbroak please ping me with a live URL of your experience?

**Comment by adewalegeorge** [comment]
Issue still persist after 2.5.0 updates

**Comment by SotirisValogiannis** [comment]
I have the same issue with version 2.6.0. I have uploaded a demo: http://goo.gl/piycX3

In chrome/firefox if the window resized the problem solved.

**Comment by annacrea** [comment]
Hello,

Did you figure out how to resolve this problem ?
I have the same issue, my slider always shows a small part of the previous slide.

Thanks for your response !

**Comment by GlauciusZacher** [comment]
A brute-force workaround that works for me, is changing the width of the outer container, in my case, just added 2px to width
`<div class="flexslider-wrapper"> 
    <div class="flexslider">
        <ul class="slides">
            <li class="slide">
                <div class="text-wrapper"> 
                    
                </div>
            </li>
        </ul>
    </div>
</div>`

**Comment by MalabarFront** [comment]
This fixes on a resize for me, so manually triggering the browser resize event after instantiating flexslider fixes it.

`$(window).trigger('resize');`

**Comment by gord2303** [comment]
@MalabarFront 's suggestion resolved my issue right away. Here's how I used his solution:
<pre>
<script type="text/javascript" charset="utf-8">
    $(window).load(function() {
    $('.flexslider').flexslider();
    $(window).trigger('resize');
});
</script>
</pre>

**Comment by iamramit** [comment]
Solution:
in your css file make ul{padding:0;margin:0},I spent like 2 hours finding the 15ps margin from left, then figured that out.

**Comment by BenRacicot** [comment]
The resize onLoad concept does not solve the issue for me at all. I created a detailed example of what is happening (with images) on #1662 . It appears in my case that the `<li>` loads at 245px then on blur then focus (Chrome tools responsive emulator) or scrolling on an actual mobile device resizes the list item to 275px. This is a brutal bug and we gotta fix it! I will post back with any ideas.

**Comment by biffmartin** [comment]
on line 877 of jquery.flexslider.js, I added this line:
`            posCalc = posCalc * 1.04;`
I was using Flexslider v2.6.4

**Comment by biffmartin** [comment]
I added this to my CSS style sheet and now the offset issue is resolved. No more offset images!

```
.loading #container {opacity: 0;}
.loading:before  { content: 'LOADING'; display: block; margin: 100px 0 0; text-align: center; color: #fff; font-weight: bold; font-size: 60px; opacity: 0.3; }
```
