### ISSUE TITLE
Flexslider slider not autoplaying on WP Elegantia Theme

### ISSUE THREAD

**Issue by jaminee** [woothemes/FlexSlider#1297]
I'm using the Elegantia Theme on wordpress 4.0
The slider used is flexslider
The slider works fine when using the arrows to navigate between slides (but doesn't autoplay)
Please tell me how to set autoplay.

this is live demo of theme.
http://themeforest.net/item/elegantia-restaurant-and-cafe-wordpress-theme/full_screen_preview/3678945
Thanks

**Comment by jeffikus** [comment]
Hi there

Unfortunately you will have to ask the theme developer to update their theme to use the latest version of FlexSlider (2.5.0) as they are still using version 2.0.0 - there have been a number of fixes surrounding autoplay and pauseHover since then.

If they get stuck, they are more than welcome to contact me via this repository - or you can link to this ticket and get them to respond directly here, I'd be happy to chat to them. Just get them to reopen this issue when they are ready!

Sorry,
