### ISSUE TITLE
Wrong order of the slides with "slide" animation, ok with fade

### ISSUE THREAD

**Issue by Kalianey** [woothemes/FlexSlider#1366]
Hello,

I'm having the following issue with flexslider: I have 4 slides, they are displaying in the right order in the source code but somehow in flexslider the 4th slider is displayed first, then in the right order the others. I found this similar issue on stackoverflow http://stackoverflow.com/questions/16608110/flexslider-animation-slide-animationloop-true-conflict but it doesn't look like there is a fix. Could you help?

Here is my code:
$('.flexslider').flexslider({
        direction: "vertical",
        animation: "slide",
        slideshow: true,
        startAt: 0,
        controlNav: true,
        directionNav: true
    });

**Comment by B-Prod** [comment]
The hack suggested in the [Stackoverflow issue](http://stackoverflow.com/questions/16608110/flexslider-animation-slide-animationloop-true-conflict#answer-23405361) mentioned above fixes this issue.

When inspecting the DOM without applying the hack, the first and last slides are cloned twice.

Removing the calls to methods.uniqueID() does not seems to break anything, since the generated IDs are not used anywhere. So it looks safe to remove the uniqueID method and the quoted lines.

**Comment by B-Prod** [comment]
Hmm this has been fixed in the latest version, so this issue may be closed.
