### ISSUE TITLE
directionNav (previous and next buttons) shown when only one slide

### ISSUE THREAD

**Issue by carolineschnapp** [woothemes/FlexSlider#1490]
I am having this issue with FlexSlider v2.6.0: if there's only slide, the left and right arrows I have set up are shown on either side.

![Alt text](https://monosnap.com/file/eJVhD1wjiqtsYIfU6ROSgfmNCdZ1JZ.png)

This is the context of building a customizable website where the website owner can upload one to six slides to his slideshow.

Code used is:

```javascript
if ( $('.regular-slider').length > 0 ) {
		$('.regular-slider.flexslider').imagesLoaded(function(){
			$('.regular-slider.flexslider').flexslider({
				animation: 'slider',
				animationSpeed: 300,
				slideshow: false,
				slideshowSpeed: 5000,
				directionNav: true,
				controlNav: true,
				keyboard: true,
				prevText: $.themeAssets.arrow_left,
				nextText: $.themeAssets.arrow_right,
				smoothHeight: true,
				start: function(slider) {
					$(window).trigger('resize');
					slider.addClass('loaded');
                    if ( $('#slider').data('loaded-index') != undefined ) {
                        $('#slider').flexslider($('#slider').data('loaded-index'));
                    }
				}
			});
		});
	}
```

**Comment by seiz** [comment]
I have the same Problem. I know there's a class .flex-disabled set for the enclosed anchor links, but that is not sufficient in my case, as ul.flex-direction-nav has layout and a height and thus affects my page-display.

In previous Versions (e.g. 2.1), directionNav was simply not printed out in the HTML Skeleton when there was only one slide. I't really like if that behavior could be restored for Version 2.6.X.

Is there a configuration option i can use to achieve the behavior like i.e. in 2.1?

Thanks a lot for a great plugin!

**Comment by seiz** [comment]
BTW: this seems to be the case, because line 1174 checks the truth of options.allowOneSlide bit doesn't take into account the defaults. 
I solved it for my case, by changing line 1174 from:
`if ( ( $slides.length === 1 && options.allowOneSlide === true ) || $slides.length === 0 ) {`
to:
`if ( ( $slides.length === 1 && options.allowOneSlide !== false ) || $slides.length === 0 ) {`

**Comment by jeffikus** [comment]
Hi guys

In terms of UX a slider should only be loaded if there are more than 1 thing to slide - otherwise it's pointless overhead. Flexslider assumes that you are using it correctly, which is why in plugins such as WooSlider it will check for 1 slide and then not load Flexslider. More than 1 slide will load it.

Thanks,
