### ISSUE TITLE
jQuery 1.8 breaks slide widths

### ISSUE THREAD

**Issue by markcarver** [woothemes/FlexSlider#752]
Because `$.outerWidth()` is now a setter (http://bugs.jquery.com/ticket/10877), it has been noted that sometimes it returns a jQuery object instead of an integer (http://bugs.jquery.com/ticket/12293).

Even though this issue apparently for whatever reason "can't be reproduced" by the jQuery team using JSFiddle, I have encountered this bug on my site with this plugin.

I recently updated to jQuery 1.8 and it broke my slider widths and animation. I traced the bug in this plugin to where the slide widths are determined. Because `$.outerWidth()` is now a setter, the `slider.boxPadding` value would return "NaN" because it couldn't subtract the width from a jQuery object:

On line 702 of jquery.flexslider.js:
`slider.boxPadding = slide.outerWidth() - slide.width();`

Replaced with:
`slider.boxPadding = slide.outerWidth(false) - slide.width();`

It will provide the same value as before, but it ensures that an integer is returned instead of a jQuery object for 1.8+.

**Comment by bewildergeist** [comment]
Thanks for filing this, I just ran into this problem on a site running v2.2.2 (and upgrading to v2.6.0 didn't help).

Two different pages with nearly identical slideshows, one worked and one didn't (since Flexslider wasn't applying `width` and `margin-left` styles to  list items and list, respectively). The specified change fixed the problem.

**Comment by by-axis41** [comment]
Yup, we also had to fix this via outerWidth(false) for jQuery 1.12 ...

**Comment by markcarver** [comment]
I have no idea why @jeffikus just closed this issue and my original PR #1069...
